services:
  db:
    image: mysql/mysql-server:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking_api
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      -
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: